apiVersion: v2

name: fixit-chart

description: Helm chart for Fixit application

type: application

version: 0.1.0

appVersion: "1.0.0"

maintainers:

  - name: vilkinss

    email: tolik_gridin@mail.ru
